### ISSUE TITLE
could not broadcast input array from shape (1000,1,1) into shape (1,1000)

### ISSUE THREAD

**Issue by gauticse2015** [artvandelay/Deep_Inside_Convolutional_Networks#1]
When i run the visualize.py  code, i got the above error as follows:-

Traceback (most recent call last):
  File "visualize.py", line 69, in <module>
    bw = net.backward(**{net.outputs[0]: caffeLabel})
  File "../python/caffe/pycaffe.py", line 167, in _Net_backward
    self.blobs[top].diff[...] = diff
ValueError: could not broadcast input array from shape (1000,1,1) into shape (1,1000)

and when i change the net.backward line as:   bw = net.backward(), it runs perfectly.
please tell me what is the problem??

**Comment by artvandelay** [comment]
It might have to do with the caffe version. Which version are you using?

**Comment by gauticse2015** [comment]
My current version of caffe is "1.0.0-rc3".

**Comment by gauticse2015** [comment]
i have modified two lines of code in visualize.py as:

caffeLabel = np.zeros((1,1000))
caffeLabel[0,label_index] = 1;

now its gives desired result.

Thanks...

**Comment by artvandelay** [comment]
I'll make the changes to the code. I wonder if only the rc version has this issue.

**Comment by artvandelay** [comment]
Closing it

**Comment by bgth** [comment]
Hi @artvandelay .. Is it possible to update the code with this change? This works for latest caffe. Thanks.
